### PR TITLE
Fix reindexing of new, changed and deleted sentences

### LINKED ISSUE #2226: Search results contains a sentence in the wrong language
Reported by [brauchinet on the Wall](https://tatoeba.org/eng/wall/show_message/34554#message_34554):

> Sentence #8281856 is misclassified as Spanish by the search engine.
It shouldn't appear in this search: https://tatoeba.org/eng/sentences/search?query=como+diferente&from=spa&to=und

### PR DESCRIPTION
**Pull request by AndiPersti**
This PR closes #2226.

Implemented changes:
- Added a `type` column to `ReindexFlags`. As explained in a [comment on the issue](https://github.com/Tatoeba/tatoeba2/issues/2226#issuecomment-650343660) that column is necessary for distinguishing between inserts/updates and removals. But instead of needing just three states we actually need four: `not indexed/changed`, `not indexed/removed`, `indexed/changed` and `indexed/removed`.
- Rewrote the parts which add entries to `ReindexFlags`. A sentence with an unknown language will never be added to that table because we do not index sentences in an unknown language.
- Modified the shell for building `manticore.conf`
- Fixed a hidden bug in the edition of a sentence in the new design. A language change was never registered in `ReindexFlags` and other tables.
- Added/Updated tests.

Besides the tests (which ensure that `ReindexFlags` is correctly updated) there is also the (updated) demo as described in [another comment on the issue](https://github.com/Tatoeba/tatoeba2/issues/2226#issuecomment-652025764) which shows that this approach should work.

In addition I did some manual testing where I've monitored the contents of `sentences`, `reindex_flags` and the `main_index` and `delta_index` for 3 different languages after each insert/update/removal of a sentence, updating delta or merging delta into main. I haven't found any issues yet.
For automatic testing we would need to start a new VM and run a script similar to the one of the demo so that's probably not doable.

(After merging this PR reindexing the whole database is necessary to start with a clean state.)

### CODE REVIEW

File: tests/TestCase/Model/Table/SentencesTableTest.php [hunk 1]
```diff
@@ -734,46 +734,72 @@ function testScriptShouldBeValidAndCheckType() {
...
-			->toList();
-		$result = Hash::extract($result, '{n}.sentence_id');
-		$this->assertEquals($expected, $result);
-	}
+    function testModifiedSentenceInUnknownDoesNotNeedReindex() {
+        $id = 9;
+        $sentence = $this->Sentence->get($id);
+        $sentence->text = 'Changed!';
+        $this->Sentence->save($sentence);
+        $result = $this->Sentence->ReindexFlags->findBySentenceId($id)->First();
```
Comment (jiru) [inline tests/TestCase/Model/Table/SentencesTableTest.php:774]: You want to write `first` instead of `First`.

File: tests/TestCase/Model/Table/SentencesTableTest.php [hunk 2]
```diff
@@ -956,6 +982,49 @@ function testEditSentence_failsBecauseWrongId() {
...
+        CurrentUser::store($this->Sentence->Users->get(7));
+        $data = [
+            'id' => '_7',
+            'value' => 'This is a lonely sentence.'
+        ];
+        $this->Sentence->editSentence($data);
+        $row = $this->Sentence->ReindexFlags->findBySentenceId(8)
+            ->where(['type' => 'change'])
+            ->first();
+        $this->assertNull($row);
```
Comment (jiru) [inline tests/TestCase/Model/Table/SentencesTableTest.php:1025]: You are editing sentence 7, but asserting on sentence 8.
I think this test, along with other ones in your PR asserting an absence of data, should be more robust because it may keep passing if `editSentence()` fails for another reason.

**Comment by jiru** [comment]
Good job fixing this issue! :+1:

(Note to self: I think we also need to update Horus so that it adds the correct entries to the reindex_flags table when it deletes a sentence.)

**Comment by AndiPersti** [comment]
Thanks for reviewing and sorry for messing up the tests.

> (Note to self: I think we also need to update Horus so that it adds the correct entries to the reindex_flags table when it deletes a sentence.)

As far as I can tell, Horus doesn't add any entries to `reindex_flags` at all.

**Comment by AndiPersti** [comment]
I've fixed the problem with the failing tests.

(I wanted to import the table definition from the app database because it would have been easier to maintain but Jenkins has no access to it.)

File: src/Model/Table/SentencesTable.php [hunk 3]
```diff
@@ -1105,19 +1127,6 @@ public function changeLanguage($sentenceId, $newLang)
         if (($ownerId == $currentUserId || CurrentUser::isModerator()) && !$this->hasAudio($sentence->id)) {
             $sentence->lang = $newLang;
             $result = $this->save($sentence);
-
-            $this->Contributions->updateLanguage($sentenceId, $newLang);
```
Comment (jiru) [inline src/Model/Table/SentencesTable.php:1109]: Correct me if I'm wrong, but this line suggests that `Contributions->updateLanguage()` is never called when the language is edited from the new design (which uses `editSentence()` instead) and that your PR fixes this problem. So we might have to fix languages in the contributions table just like in #2387. Could you confirm this and add a unit test?

Comment (AndiPersti) [reply src/Model/Table/SentencesTable.php:1109]: Yes, `editSentence` didn't do all the changes that `changeLanguage` did.
A few weeks ago I've added [sentence #7841656 on dev](https://dev.tatoeba.org/deu/sentences/show/7841656) as Latin:
```
MariaDB [tatoeba]> select lang from sentences where id = 7841656;
+------+
| lang |
+------+
| lat  |
+------+
1 row in set (0.001 sec)

MariaDB [tatoeba]> select * from contributions where sentence_id = 7841656;
+-------------+---------------+----------------+------------------+--------+--------------+--------+---------+---------------------+----------+----------+
| sentence_id | sentence_lang | translation_id | translation_lang | script | text         | action | user_id | datetime            | type     | id       |
+-------------+---------------+----------------+------------------+--------+--------------+--------+---------+---------------------+----------+----------+
|     7841656 | lat           |           NULL | NULL             | NULL   | lorem ipsum  | insert |   70604 | 2020-04-24 14:20:04 | sentence | 26641857 |
|     7841656 | NULL          |           NULL | NULL             | NULL   | CC BY 2.0 FR | insert |   70604 | 2020-04-24 14:20:04 | license  | 26641858 |
+-------------+---------------+----------------+------------------+--------+--------------+--------+---------+---------------------+----------+----------+
2 rows in set (0.001 sec)
```
Now I've changed the language to German using the new design:
```
MariaDB [tatoeba]> select lang from sentences where id = 7841656;
+------+
| lang |
+------+
| deu  |
+------+
1 row in set (0.001 sec)

MariaDB [tatoeba]> select * from contributions where sentence_id = 7841656;
+-------------+---------------+----------------+------------------+--------+--------------+--------+---------+---------------------+----------+----------+
| sentence_id | sentence_lang | translation_id | translation_lang | script | text         | action | user_id | datetime            | type     | id       |
+-------------+---------------+----------------+------------------+--------+--------------+--------+---------+---------------------+----------+----------+
|     7841656 | lat           |           NULL | NULL             | NULL   | lorem ipsum  | insert |   70604 | 2020-04-24 14:20:04 | sentence | 26641857 |
|     7841656 | NULL          |           NULL | NULL             | NULL   | CC BY 2.0 FR | insert |   70604 | 2020-04-24 14:20:04 | license  | 26641858 |
+-------------+---------------+----------------+------------------+--------+--------------+--------+---------+---------------------+----------+----------+
2 rows in set (0.000 sec)
```

But now that you have asked I wonder if the old behavior (changing the languages in `contributions` for old rows) is really a good idea. I've considered the entries in `contributions` as read-only and the log would allow us to reconstruct how a sentence changed over time. But "rewriting the history" makes this impossible.

Shouldn't we rather implement #533?

Furthermore even using the old design we do not update the translation language in `contributions` ([7842015](https://dev.tatoeba.org/deu/sentences/show/7842015), [7842016](https://dev.tatoeba.org/deu/sentences/show/7842016)):
Before:
```
MariaDB [tatoeba]> select id, lang, created, modified from sentences where id in (7842015, 7842016);
+---------+------+---------------------+---------------------+
| id      | lang | created             | modified            |
+---------+------+---------------------+---------------------+
| 7842015 | deu  | 2020-07-13 04:57:39 | 2020-07-13 04:57:39 |
| 7842016 | eng  | 2020-07-13 04:58:01 | 2020-07-13 04:58:01 |
+---------+------+---------------------+---------------------+
2 rows in set (0.001 sec)

MariaDB [tatoeba]> select sentence_id, sentence_lang, translation_id, translation_lang, action, type, datetime from contributions where sentence_id in (7842015
, 7842016);
+-------------+---------------+----------------+------------------+--------+----------+---------------------+
| sentence_id | sentence_lang | translation_id | translation_lang | action | type     | datetime            |
+-------------+---------------+----------------+------------------+--------+----------+---------------------+
|     7842015 | deu           |           NULL | NULL             | insert | sentence | 2020-07-13 04:57:39 |
|     7842015 | NULL          |           NULL | NULL             | insert | license  | 2020-07-13 04:57:40 |
|     7842015 | NULL          |        7842016 | NULL             | insert | link     | 2020-07-13 04:58:01 |
|     7842016 | eng           |           NULL | NULL             | insert | sentence | 2020-07-13 04:58:01 |
|     7842016 | NULL          |           NULL | NULL             | insert | license  | 2020-07-13 04:58:01 |
|     7842016 | NULL          |        7842015 | NULL             | insert | link     | 2020-07-13 04:58:01 |
+-------------+---------------+----------------+------------------+--------+----------+---------------------+
6 rows in set (0.001 sec)
```
After:
```
MariaDB [tatoeba]> select id, lang, created, modified from sentences where id in (7842015, 7842016);
+---------+------+---------------------+---------------------+
| id      | lang | created             | modified            |
+---------+------+---------------------+---------------------+
| 7842015 | rus  | 2020-07-13 04:57:39 | 2020-07-13 05:05:18 |
| 7842016 | spa  | 2020-07-13 04:58:01 | 2020-07-13 05:05:22 |
+---------+------+---------------------+---------------------+
2 rows in set (0.001 sec)

MariaDB [tatoeba]> select sentence_id, sentence_lang, translation_id, translation_lang, action, type, datetime from contributions where sentence_id in (7842015, 7842016);
+-------------+---------------+----------------+------------------+--------+----------+---------------------+
| sentence_id | sentence_lang | translation_id | translation_lang | action | type     | datetime            |
+-------------+---------------+----------------+------------------+--------+----------+---------------------+
|     7842015 | rus           |           NULL | NULL             | insert | sentence | 2020-07-13 04:57:39 |
|     7842015 | rus           |           NULL | NULL             | insert | license  | 2020-07-13 04:57:40 |
|     7842015 | rus           |        7842016 | NULL             | insert | link     | 2020-07-13 04:58:01 |
|     7842016 | spa           |           NULL | NULL             | insert | sentence | 2020-07-13 04:58:01 |
|     7842016 | spa           |           NULL | NULL             | insert | license  | 2020-07-13 04:58:01 |
|     7842016 | spa           |        7842015 | NULL             | insert | link     | 2020-07-13 04:58:01 |
+-------------+---------------+----------------+------------------+--------+----------+---------------------+
6 rows in set (0.001 sec)
```
On dev the most recent entry in `contributions` that has a `translation_lang` is from 2010:
```
MariaDB [tatoeba]> select max(datetime) from contributions where length(translation_lang) > 0;
+---------------------+
| max(datetime)       |
+---------------------+
| 2010-04-06 19:28:07 |
+---------------------+
1 row in set (14.789 sec)
```

And you can also see that calling `Contributions->updateLanguage()` modifies `sentence_lang` for every row whereas we don't store a value for `sentence_lang` when we log license insertion and link insertion.

I'm afraid contributions logging needs some fixing. So do you still want to have the unit test in this PR?

Comment (jiru) [reply src/Model/Table/SentencesTable.php:1109]: About `contributions.translation_lang`, maybe this field was used somehow in the past, but now we are not displaying this information anywhere, so it makes sense that it is currently not updated. I think we could as well remove that column.

As for `contributions.sentence_lang`, you have a point. It’s okay not to include a unit test.
